version: 0.2

env:
  variables:
    RESOURCE_DB: "backend/resources/database"
    RESOURCE_COGNITO: "backend/resources/cognito"
    RESOURCE_GATEWAY: "backend/resources/gateway"

    LAYERS: "backend/layers"

    SERVICE_AUTH: "backend/services/auth"
    SERVICE_CUSTOMERS: "backend/services/customers"
    SERVICE_USERS: "backend/services/users"
    SERVICE_MIGRATIONS: "backend/services/migrations"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - aws s3 ls
      # - npm install -g serverless@1.61.2
      # - cd backend && npm ci && cd -
  #     - |-
  #         if [ "$DEPLOY_RESOURCE_DB" -eq "1" ]; then
  #           cd ${RESOURCE_DB} && npm ci && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_RESOURCE_COGNITO" -eq "1" ]; then
  #           cd ${RESOURCE_COGNITO} && npm ci && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_RESOURCE_GATEWAY" -eq "1" ]; then
  #           cd ${RESOURCE_GATEWAY} && npm ci && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_LAYER_HELPER" -eq "1" ]; then
  #           cd ${LAYERS} && npm ci && cd -
  #           cd ${LAYERS}/helper_lib && npm ci && cd -
  #           cd ${LAYERS}/helper_lib/dist/nodejs && npm ci && cd -
  #           cd ${LAYERS}/models_lib && npm ci && cd -
  #           cd ${LAYERS}/models_lib/dist/nodejs && npm ci && cd -
  #         fi
  #
  #     - |-
  #         if [ "$DEPLOY_SERVICE_AUTH" -eq "1" ]; then
  #           cd ${SERVICE_AUTH} && npm ci && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_SERVICE_USER" -eq "1" ]; then
  #           cd ${SERVICE_USERS} && npm ci && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_SERVICE_CUSTOMER" -eq "1" ]; then
  #           cd ${SERVICE_CUSTOMERS} && npm ci && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_SERVICE_MIGRATION" -eq "1" ]; then
  #           cd ${SERVICE_MIGRATIONS} && npm ci && cd -
  #         fi
  #   finally:
  #     - echo Installation finished
  # pre_build:
  #   commands:
  #      #Compile layers
  #      - |-
  #         if [ "$DEPLOY_LAYER_HELPER" -eq "1" ]; then
  #           cd ${LAYERS}
  #           cd helper_lib && npm run compile
  #           cd ../
  #           cd models_lib && npm run compile
  #           cd ../../../
  #         fi
  # build:
  #   commands:
  #     - |-
  #         if [ "$DEPLOY_RESOURCE_DB" -eq "1" ]; then
  #           cd ${RESOURCE_DB} && serverless deploy && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_RESOURCE_COGNITO" -eq "1" ]; then
  #           cd ${RESOURCE_COGNITO} && serverless deploy && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_RESOURCE_GATEWAY" -eq "1" ]; then
  #           cd ${RESOURCE_GATEWAY} && serverless deploy && cd -
  #         fi
  #
  #     - |-
  #         if [ "$DEPLOY_LAYER_HELPER" -eq "1" ]; then
  #           cd ${LAYERS} && serverless deploy && cd -
  #         fi
  #
  #     - |-
  #         if [ "$DEPLOY_SERVICE_AUTH" -eq "1" ]; then
  #           cd ${SERVICE_AUTH} && serverless deploy --alias=${ALIAS} && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_SERVICE_USER" -eq "1" ]; then
  #           cd ${SERVICE_USERS} && serverless deploy --alias=${ALIAS} && cd -
  #         fi
  #     - |-
  #         if [ "$DEPLOY_SERVICE_CUSTOMER" -eq "1" ]; then
  #           cd ${SERVICE_CUSTOMERS} && serverless deploy --alias=${ALIAS} && cd -
  #         fi
  # post_build:
  #   commands:
  #     - echo Executing migrations
  #     - |-
  #         if [ "$DEPLOY_SERVICE_MIGRATION" -eq "1" ]; then
  #           cd ${SERVICE_MIGRATIONS} && serverless migrations-up && cd -
  #         fi

    finally:
      - echo Build finished
