version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - cd ${SERVICE_PATH} && npm ci
    finally:
      - echo Installation done 
  build:
    commands:
      - mkdir -p target/dev
      - mkdir -p target/qa
      - mkdir -p target/uat
      - mkdir target/prod
      - serverless package --package target/dev --stage dev -v
      - serverless package --package target/qa --stage qa -v
      - serverless package --package target/uat --stage uat -v
      - serverless package --package target/prod --stage prod -v
    finally:
      - echo Packaging done

artifacts:
  files:
  - ${SERVICE_PATH}/target/**/*
  - ${SERVICE_PATH}/node_modules/**/*
  - ${SERVICE_PATH}/serverless.yml
  - serverless.common.yml
  - codebuild/buildspec-database-deploy.yml

cache:
  paths:
    - ${SERVICE_PATH}/node_modules
