version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
    finally:
      - echo Installation done 
  build:
    commands:
      - cd ${SERVICE_PATH}
      - SLS_DEBUG=1 serverless deploy --stage ${STAGE} --package ./target/${STAGE} -v
    finally:
      - echo Deploy done