version: 0.2

env:
  variables:
    SERVICE_AUTH: "backend/services/auth"
    SERVICE_CUSTOMERS: "backend/services/customers"
    SERVICE_USERS: "backend/services/users"
    SERVICE_MIGRATIONS: "backend/services/migrations"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless@1.61.2
    finally:
      - echo Installation finished

  pre_build:
    commands:
       # Migrations
      # - cd ${SERVICE_MIGRATIONS}
      # - serverless migrations-up --package target/test -v && cd -
  build:
    commands:
      # DB
      - cd ${SERVICE_AUTH}
      - serverless deploy --package target/test -v && cd -
      # Cognito
      - cd ${SERVICE_CUSTOMERS}
      - serverless deploy --package target/test -v && cd -
      # Gateway
      - cd ${SERVICE_USERS}
      - serverless deploy --package target/test -v && cd -
      # Layers
      # - cd ${LAYERS}
      # - echo `pwd`
      # - SLS_DEBUG=1 serverless deploy --package target -v && cd -

    finally:
      - echo Packaging finished
