version: 0.2

env:
  variables:
    RESOURCE_DB: "backend/resources/database"
    RESOURCE_COGNITO: "backend/resources/cognito"
    RESOURCE_GATEWAY: "backend/resources/cognito"

    LAYERS: "backend/layers"

    SERVICE_AUTH: "backend/services/auth"
    SERVICE_USERS: "backend/services/users"
    SERVICE_CUSTOMERS: "backend/services/customers"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless@1.61.2
    finally:
      - echo Installation finished
  build:
    commands:
      # DB
      - cd ${RESOURCE_DB}
      - serverless deploy --package target/test -v && cd -
      # Cognito
      - cd ${RESOURCE_COGNITO}
      - serverless deploy --package target/test -v && cd -
      # Gateway
      - cd ${RESOURCE_GATEWAY}
      - serverless deploy --package target/test -v && cd -
      # Cognito
      - cd ${LAYERS}
      - SLS_DEBUG=1 serverless deploy --package target -v && cd -
    finally:
      - echo Deploy finished
