version: 0.2

env:
  variables:
    RESOURCE_DB: "backend/resources/database"
    RESOURCE_COGNITO: "backend/resources/cognito"
    RESOURCE_GATEWAY: "backend/resources/gateway"

    LAYERS: "backend/layers"

    SERVICE_AUTH: "backend/services/auth"
    SERVICE_USERS: "backend/services/users"
    SERVICE_CUSTOMERS: "backend/services/customers"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Time `date`
      - npm install -g serverless@1.61.2
      - echo Time `date`
      - cd ${RESOURCE_DB} && npm ci && cd -
      - cd ${RESOURCE_COGNITO} && npm ci && cd -
      - cd ${LAYERS} && npm ci && cd -
      - cd ${LAYERS}/helper_lib && npm ci && cd -
      - cd ${LAYERS}/users_lib && npm ci && cd -
      - echo Time `date`
    finally:
      - echo Installation finished
  pre_build:
    commands:
       #Compile layers
      - cd ${LAYERS}
      - cd helper_lib && npm run compile
      - cd ../
      - cd users_lib && npm run compile
      - cd ../../../
  build:
    commands:
      # TODO Add tests and lint
      - mkdir -p ${RESOURCE_DB}/target/test
      - mkdir -p ${RESOURCE_COGNITO}/target/test
      - mkdir -p ${RESOURCE_GATEWAY}/target/test
      - mkdir -p ${LAYERS}/target
      - echo Time `date`
      # DB
      - echo `pwd`
      - cd ${RESOURCE_DB} && serverless package --package target/test && cd -
      - echo Time `date`
      # Cognito
      - echo `pwd`
      - cd ${RESOURCE_COGNITO} && serverless package --package target/test && cd -
      - echo Time `date`
      # Gateway
      - echo Time `date`
      - echo `pwd`
      - cd ${RESOURCE_GATEWAY} && serverless package --package  target/test && cd -

      # Layers
      - echo Time `date`
      - echo `pwd`
      - cd ${LAYERS} && serverless deploy && cd -

      - echo Time `date`

    finally:
      - echo Packaging finished

artifacts:
  files:
  # DB
  - ${RESOURCE_DB}/target/**/*
  - ${RESOURCE_DB}/node_modules/**/*
  - ${RESOURCE_DB}/serverless.yml
  # Cognito
  - ${RESOURCE_COGNITO}/target/**/*
  - ${RESOURCE_COGNITO}/node_modules/**/*
  - ${RESOURCE_COGNITO}/serverless.yml
  # Gateway
  - ${GATEWAY}/target/**/*
  - ${GATEWAY}/serverless.yml
  # Layers
  - ${LAYERS}/helper_lib/**/*
  - ${LAYERS}/users_lib/**/*
  - ${LAYERS}/target/**/*
  - ${LAYERS}/node_modules/**/*
  - ${LAYERS}/serverless.yml
  # Common
  - serverless.common.yml
  - codebuild/buildspec-deploy-resources.yml
  - backend/resources/stack-outputs/*

cache:
  paths:
    - '/usr/local/lib/node_modules/serverless/**/*'
    - 'node_modules/**/*'
    - `${RESOURCE_DB}/node_modules`
    - `${RESOURCE_COGNITO}/node_modules`
