service: mypay-users

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-stack-output
  - serverless-aws-alias
  - serverless-plugin-ifelse

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    COGNITO_USER_POOL_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolId}
    STAGE: ${self:custom.stage}
    DB_RESOURCE_ARN: ${file(../../resources/stack-outputs/database-${self:custom.stage}.yml):DbClusterArn}
    SECRET_ARN: ${file(../../resources/stack-outputs/database-${self:custom.stage}.yml):SecretManagerArn}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds-data:ExecuteStatement
        - rds-data:BatchExecuteStatement
        - rds-data:BeginTransaction
        - rds-data:CommitTransaction
        - rds-data:RollbackTransaction
      Resource: "*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        'Fn::ImportValue': ${self:custom.stage}-SecretManagerArn
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminEnableUser
        - cognito-idp:AdminDisableUser
      Resource:
        'Fn::ImportValue': ${self:custom.stage}-CognitoUserPoolArn
  
custom:
  defaultStage: ${file(../../../serverless.common.yml):custom.defaultStage}
  stage: ${file(../../../serverless.common.yml):custom.stage}
  baseApiPath: ${file(../../../serverless.common.yml):custom.baseApiPath}

  usersEntityPath: ${self:custom.baseApiPath}/users
  

  offlineBundles:
    aws: ${file(bundle-aws.yml)}
    local: ${file(bundle-offline.yml)}

  bundle:
    sourcemaps: true
    externals:
      - mypay-helpers
      - users-helpers
    linting: false #Ignore for compilation
    ignorePackages:
      - pg-hstore
      # only on aws
      - ../../../layers/helper_lib/src/response.helper
      - ../../../layers/users_lib/src/user
      - ../../../layers/helper_lib/src/mysql-db
  
  output:
    file: stack-outputs/user-${self:provider.alias}.yml
  
functions:
  - ${file(functions.yml)}