service: mypay-customers

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-plugin-custom-roles

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    COGNITO_USER_POOL_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolId}
    COGNITO_CLIENT_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolClientId}
  
custom:
  defaultStage: ${file(../../../serverless.common.yml):custom.defaultStage}
  resourcesStages: ${file(../../../serverless.common.yml):custom.resourcesStages}
  resourceStage: ${file(../../../serverless.common.yml):custom.resourcesStage}
  stage: ${file(../../../serverless.common.yml):custom.stage}
  baseApiPath: ${file(../../../serverless.common.yml):custom.baseApiPath}

  businessEntityPath: ${self:custom.baseApiPath}/business


  bundle:
    sourcemaps: false
    externals:
      - mypay-helpers
    linting: false #Ignore for compilation
    ignorePackages:
      # only on aws
      - ../../../layers/helper_lib/src/response.helper
  
functions:
  ServiceCustomersHierarchy:
    handler: functions/get-hierarchy-handler.getHierarchy
    events:
      - http:
          path: ${self:custom.businessEntityPath}/getHierarchy
          method: get
          cors: true
    layers:
      - ${file(../../layers/layers-outputs.yml):HelperlibLambdaLayerQualifiedArn}
  ServiceBusinessGet:
    handler: functions/business/get-businesses-handler.getBusinesses
    events:
      - http:
          path: ${self:custom.businessEntityPath}
          method: get
          cors: true
    layers:
      - ${file(../../layers/layers-outputs.yml):HelperlibLambdaLayerQualifiedArn}

  ServiceBusinessGetById:
    handler: functions/business/get-business-handler.getBusiness
    events:
      - http:
          path: ${self:custom.businessEntityPath}/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
    layers:
      - ${file(../../layers/layers-outputs.yml):HelperlibLambdaLayerQualifiedArn}

  ServiceBusinessCreate:
    handler: functions/business/create-business-handler.createBusiness
    events:
      - http:
          path: ${self:custom.businessEntityPath}
          method: post
          cors: true
    layers:
      - ${file(../../layers/layers-outputs.yml):HelperlibLambdaLayerQualifiedArn}

  ServiceBusinessUpdate:
    handler: functions/business/update-business-handler.updateBusiness
    events:
      - http:
          path: ${self:custom.businessEntityPath}/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
    layers:
      - ${file(../../layers/layers-outputs.yml):HelperlibLambdaLayerQualifiedArn}

  ServiceBusinessDelete:
    handler: functions/business/delete-business-handler.deleteBusiness
    events:
      - http:
          path: ${self:custom.businessEntityPath}/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
    layers:
      - ${file(../../layers/layers-outputs.yml):HelperlibLambdaLayerQualifiedArn}
