service: mypay-customers

plugins:
  - serverless-offline
  - serverless-bundle
  - serverless-stack-output
  - serverless-aws-alias

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    COGNITO_USER_POOL_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolId}
    COGNITO_CLIENT_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolClientId}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds-data:ExecuteStatement
        - rds-data:BatchExecuteStatement
        - rds-data:BeginTransaction
        - rds-data:CommitTransaction
        - rds-data:RollbackTransaction
      Resource: '*'
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        'Fn::ImportValue': ${self:custom.stage}-SecretManagerArn
  
custom:
  defaultStage: ${file(../../../serverless.common.yml):custom.defaultStage}
  stage: ${file(../../../serverless.common.yml):custom.stage}
  baseApiPath: ${file(../../../serverless.common.yml):custom.baseApiPath}

  businessEntityPath: ${self:custom.baseApiPath}/business


  bundle:
    sourcemaps: false
    externals:
      - mypay-helpers
    linting: false #Ignore for compilation
    ignorePackages:
      # only on aws
      - ../../../layers/helper_lib/src/response.helper

  output:
    file: stack-outputs/customer-${self:provider.alias}.yml
  
functions:
  - ${file(functions.yml)}