name: Layers

on:
  pull_request:
    branches:
      - master
      - development
      - dev/workflow
  push:
    branches:
      - master
      - development
      - dev/workflow

env:
  LAYER_HAS_UPDATES: false

jobs:
  CheckLayerUpdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkSourceCommit
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})

      - name: checkForLayer
        run: |
          for i in ${{ steps.filepath.outputs.commitpath }}; do
            echo item: $i
            if [[ $i =~ ^backend/layers ]]; then
              echo "::set-env name=LAYER_HAS_UPDATES::true"
              break
            fi
          done
  LayersJob:
    if: $LAYER_HAS_UPDATES
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install layer packages
        run: |
          npm install
        working-directory: backend/layers
      - name: Install helper_lib packages
        run: |
          npm install
        working-directory: backend/layers/helper_lib
      - name: Compile helper_lib
        run: |
          npm run-script compile
        working-directory: backend/layers/helper_lib
      - name: Serverless package
        run: |
          npx serverless package -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: backend/layers
