name: Layers

on:
  pull_request:
    branches:
      - master
      - development
      - dev/workflow
  push:
    branches:
      - master
      - development
      - dev/workflow

jobs:
  CheckLayerUpdated:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.updates.outputs.LAYER_HAS_UPDATES }}
    steps:
      - uses: actions/checkout@v1
      - name: checkSourceCommit
        id: filepath
        run: |
          echo ::set-output name=commitpath::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
      - name: checkForLayer
        id: updates
        run: |
          for i in ${{ steps.filepath.outputs.commitpath }}; do
            echo item: $i
            if [[ $i =~ ^backend/layers ]]; then
              echo ::set-output name=LAYER_HAS_UPDATES::'1'
              break
            fi
          done
      - name: echoResult
        run: |
          echo ${{ steps.updates.outputs.LAYER_HAS_UPDATES }}
  LayersJob:
    needs: CheckLayerUpdated
    if: ${{needs.CheckLayerUpdated.outputs.output1 == '1'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install layer packages
        run: |
          npm install
        working-directory: backend/layers
      - name: Install helper_lib packages
        run: |
          npm install
        working-directory: backend/layers/helper_lib
      - name: Compile helper_lib
        run: |
          npm run-script compile
        working-directory: backend/layers/helper_lib
      - name: Serverless package
        run: |
          npx serverless deploy -v
          # cp layers-outputs.yml backend/layers/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: backend/layers

      - name: Commit files # commit the output folder
        run: |
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add ./backend/layers/layers-outputs.yml
          git commit -m "Add changes"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          branch: development #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
